[package]
name = "krill_cms_proxy"
version = "0.2.0"
authors = ["Tim Bruijnzeels <tim@nlnetlabs.nl>", "Martin Hoffmann <martin@nlnetlabs.nl>"]

[dependencies]
base64        = "^0.10"
bcder         = "^0.3"
bytes         = "^0.4"
chrono        = { version = "^0.4", features = ["serde"] }
derive_more   = "^0.13"
hex           = "^0.3"
openssl       = { version = "^0.10", features = ["v110"] }
rpki          = "^0.5"
serde         = { version = "^1.0", features = ["derive"] }
serde_json    = "^1.0"
xml-rs        = "0.8.0"

# Both needed for logging, setup is done in main project
fern         = "^0.5"
log          = "^0.4"

[dependencies.krill_commons]
path = "../commons"
version = "0.2.0"
