[package]
name = "rpki-publication-server"
version = "0.1.0"
authors = ["Tim Bruijnzeels <tim@nlnetlabs.nl>", "Martin Hoffmann <martin@nlnetlabs.nl>"]

[dependencies]
rpki    = { git="https://github.com/NLnetLabs/rpki-rs.git" }
base64  = "^0.9"
bytes   = "^0.4"
hyper   = "0.12"
futures = "0.1"
failure = "^0.1"
xml-rs  = "0.8.0"

