[package]
name = "rpubd"
version = "0.1.0"
authors = ["Tim Bruijnzeels <tim@nlnetlabs.nl>", "Martin Hoffmann <martin@nlnetlabs.nl>"]

[dependencies]
actix        = "^0.7"
actix-web    = "^0.7"
base64       = "^0.9"
bcder        = "^0.1"
bytes        = "^0.4"
chrono       = { version = "^0.4", features = ["serde"] }
clap         = "^2.32"
failure      = "^0.1"
fern         = "^0.5"
futures      = "0.1"
hex          = "^0.3"
lazy_static  = "^1.1"
log          = "^0.4"
openssl      = "^0.10"
pretty       = "0.5.2"
rand         = "^0.5"
reqwest      = "^0.9"
rpki         = { version = "^0.2", features = ["softkeys"] }
serde        = { version = "^1.0", features = ["rc"] }
serde_derive = "^1.0"
serde_json   = "^1.0"
syslog       = "^4.0"
toml         = "^0.4"
tokio        = "^0.1"
xml-rs       = "0.8.0"

[patch.crates-io]
rpki = { git="https://github.com/NLnetLabs/rpki-rs.git", branch="generate-signed-publication-protocol-messages", features = ["softkeys"]}
