[workspace]
members = [ "ca", "client", "cms_proxy", "commons", "daemon", "pubc", "pubd" ]

[patch.crates-io]
rpki = { git="https://github.com/NLnetLabs/rpki-rs.git", branch="ring-0.14" }
bcder = { git="https://github.com/NLnetLabs/bcder.git" }
