[package]
name    = "krill"
version = "0.6.3"
edition = "2018"
authors = [ "The NLnet Labs RPKI team <rpki-team@nlnetlabs.nl>" ]
description = "Resource Public Key Infrastructure (RPKI) daemon"
homepage = "https://www.nlnetlabs.nl/projects/rpki/krill/"
repository = "https://github.com/NLnetLabs/krill"
keywords = ["rpki", "routing-security", "bgp"]
readme = "README.md"
license = "MPL-2.0"

[dependencies]
base64          = "^0.10"
bcder           = "0.5.0"
bytes           = "^0.5"
chrono          = { version = "^0.4", features = ["serde"] }
clap            = "^2.32"
clokwerk        = "^0.1"
derive_more     = "^0.13"
fern            = { version = "^0.5", features = ["syslog-4"] }
futures         = "0.3.4"
futures-util    = "0.3.4"
hex             = "^0.3"
hyper           = "^0.13"
log             = "^0.4"
openssl         = { version = "^0.10", features = ["v110"] }
pretty          = "0.5.2" # for testing
rand            = "^0.5"
reqwest         = { version = "0.10.4", features = ["blocking", "json"] }
rpki            = "0.9.0"
serde           = { version = "^1.0", features = ["derive"] }
serde_json      = "^1.0"
syslog          = "^4.0"
tokio           = { version = "=0.2.13", features = ["rt-core", "macros", "time"] }
tokio-proto     = "0.1.1"
tokio-rustls    = "0.13.0"
toml            = "^0.4"
uuid            = { version = "0.7", features = [ "v4"] }
xml-rs          = "0.8.0"

[target.'cfg(unix)'.dependencies]
libc		    = "^0.2"
syslog		    = "^4.0"

[build-dependencies]
ignore          = "^0.4"

[features]
default = []
extra-debug = [ "rpki/extra-debug" ]
static-openssl = [ "openssl/vendored" ]

# Configuration for cargo-deb (https://github.com/mmstick/cargo-deb)
# Builds a Debian package in target/debian/ when invoked with: cargo deb
# Configuration valid as of cargo-deb v1.23.1.
[package.metadata.deb]
priority = "optional"
section = "net"

# Sstatically link with OpenSSL when building a Debian package because the
# newest OpenSSL available on Ubuntu 16.04 at the time of writing is 1.0.2g
# (see: https://packages.ubuntu.com/xenial/openssl) while Krill requires
# OpenSSL >= 1.1.0.
features = [ "static-openssl" ]

# Manually specify depends instead of using "$auto" because when building
# on a GitHub Actions Ubuntu 16.04 runner cargo-deb detects much newer
# versions of these libraries than are available when testing apt-get install
# on stock (Docker/DigitalOcean) Ubuntu 16.04, causing installation to fail
# if "$auto" is used.
depends = "libc6 (>= 2.23), libgcc1 (>= 1:6.0.1)"

extended-description = """\
Krill is a free, open source RPKI Certificate Authority that lets you run
delegated RPKI under one or multiple Regional Internet Registries (RIRs).
Through its built-in publication server, Krill can publish Route Origin
Authorisations (ROAs) on your own servers or with a third party.

This package contains the krill daemon and krillc CLI binaries.

For more information visit https://rpki.readthedocs.io/en/latest/krill/."""
