[package]
name = "rpubd"
version = "0.1.0"
authors = ["Tim Bruijnzeels <tim@nlnetlabs.nl>", "Martin Hoffmann <martin@nlnetlabs.nl>"]

[dependencies]
ber          = { git="https://github.com/NLnetLabs/ber-rs.git" }
rpki         = { git="https://github.com/NLnetLabs/rpki-rs.git", features = [ "softkeys" ] }
base64       = "^0.9"
bytes        = "^0.4"
clap         = "^2.32"
hyper        = "0.12"
futures      = "0.1"
failure      = "^0.1"
lazy_static  = "^1.1"
serde        = "^1.0"
serde_derive = "^1.0"
serde_json   = "^1.0"
toml         = "^0.4"
xml-rs       = "0.8.0"

