[workspace]
members = [ "ca", "client", "commons", "daemon", "pubc", "pubd" ]

[patch.crates-io]
rpki = { git="https://github.com/NLnetLabs/rpki-rs.git" }
bcder = { git="https://github.com/NLnetLabs/bcder.git" }
