# Specify the ip address and port number that the server will use.
ip             = "127.0.0.1"
port           = 3000

# Specify the directory where the publication server will store its data.
# Note that clustering through a shared data directory is not supported.
# But, we plan to look into a proper clustering solution later.
data_dir       = "./data"

# Specify the directory where to read publisher.xml files.
# Note that 'publisher_handle' must be unique, so verify them before dropping
# files here. At some point a UI/API will be introduced for this.
pub_xml_dir    = "./publishers"

# Specify the base rsync repository for this server. Publishers will get
# a base URI that is based on the 'publisher_handle' in the XML file.
#
# Note, you should set up an rsync daemon to expose $data_dir/rsync to serve
# this data. The uri defined here should match the module name in your rsync
# configuration.
rsync_base     = "rsync://127.0.0.1/repo/"

# Specify the notify SIA for this server. This will be reported in the
# response.xml files to publishers so that they can include the proper SIA
# in their certificates.
rrdp_base_uri  = "http://127.0.0.1:3000/rrdp/"

# Specify the base service URI where publishers can connect.
service_uri    = "http://127.0.0.1:3000/rfc8181/"