{{- if and .Values.krillConf.auth_token (not .Values.krillConf.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "krill.authTokenSecretName" . }}
  labels:
    {{- include "krill.labels" . | nindent 4 }}
data:
  auth_token: {{ .Values.krillConf.auth_token | b64enc | quote }}
{{- end}}
