{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "krill.fullname" . }}
  {{- if .Values.metrics.serviceMonitor.namespace }}
  namespace: {{ .Values.metrics.serviceMonitor.namespace }}
  {{- end }}
  labels:
    {{- include "krill.labels" . | nindent 4 }}
spec:
  endpoints:
  - port: {{ default "http" .Values.metrics.serviceMonitor.port }}
    interval: {{ default "30s" .Values.metrics.serviceMonitor.interval }}
    path: {{ default "/metrics" .Values.metrics.serviceMonitor.path }}
    {{- with .Values.metrics.serviceMonitor.tlsConfig }}
    tlsConfig:
      {{ toYaml . | trim | nindent 6 }}
    {{- end }}
  jobLabel: {{ template "krill.fullname" . }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "krill.selectorLabels" . | nindent 6 }}
{{- end -}}
